# Generated by Django 5.1.4 on 2024-12-11 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
        ('posts', '0013_alter_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when bookmark was created'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='folder',
            field=models.ForeignKey(help_text='Folder containing the bookmark', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='bookmarks.bookmarkfolder'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='owner',
            field=models.ForeignKey(help_text='User who created the bookmark', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='post',
            field=models.ForeignKey(help_text='Post being bookmarked', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='posts.post'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('owner', 'post', 'folder'), name='unique_bookmark', violation_error_message='This post is already bookmarked in this folder.'),
        ),
    ]
